# Generated by Django 3.0.5 on 2020-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('student', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=100, unique=True)),
                ('organization', models.EmailField(max_length=100)),
                ('enrol_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_booking', models.DateTimeField()),
                ('total_credits', models.IntegerField()),
                ('remaining_credits', models.IntegerField()),
            ],
        ),
    ]
